apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-pro
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: python
        resources: 
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"